import React from "react";

export const ActivityConditions = {
  extra: {
    type: ["서포터즈", "기자단", "봉사", "강연/멘토링"],
    field: [
      "금융/경제",
      "헬스/스포츠",
      "의료/제약/보건",
      "요리/식품",
      "화학/에너지/환경",
      "유통/물류",
      "제조/생산",
      "IT/기술",
      "아이디어/발명",
      "디자인",
      "건축/설계/인테리어",
      "미디어",
      "문학/음악/무용",
      "창업/스타트업",
      "교육/행사",
    ],
    organizer: [
      "정부/공공기관",
      "공기업",
      "대기업",
      "외국계기업",
      "중견/중소/벤처기업",
      "신문/방송/언론",
      "비영리/협회/재단",
      "해외",
      "기타",
    ],
    district: [
      "서울",
      "인천",
      "경기",
      "부산",
      "대구",
      "광주",
      "대전",
      "울산",
      "세종",
      "강원",
      "충북",
      "충남",
      "전북",
      "전남",
      "경북",
      "경남",
      "제주",
      "온라인",
      "지역무관",
    ],
  },
  contest: {
    type: [
      "아이디어/기획서",
      "문학/에세이/시나리오",
      "드론/자동차",
      "캐릭터/만화/일러스트",
      "영상/사진/카드뉴스",
      "웹/앱",
      "설계/모형",
    ],
    field: [
      "금융/경제",
      "헬스/스포츠",
      "의료/제약/보건",
      "요리/식품",
      "화학/에너지/환경",
      "유통/물류",
      "제조/생산",
      "IT/기술",
      "아이디어/발명",
      "디자인",
      "건축/설계/인테리어",
      "미디어",
      "문학/음악/무용",
      "창업/스타트업",
      "교육/행사",
    ],
    organizer: [
      "정부/공공기관",
      "공기업",
      "대기업",
      "외국계기업",
      "중견/중소/벤처기업",
      "신문/방송/언론",
      "비영리/협회/재단",
      "해외",
      "기타",
    ],
    prize: [
      "5천만원 이상",
      "3~5천만원",
      "1~3천만원",
      "1천마원 이하",
      "입사시 가산점",
      "인턴 채용",
      "정직원 채용",
      "기타",
    ],
  },
};

export const ExtraSelected = {
  type: { btn_0: false, btn_1: false, btn_2: false, btn_3: false },
  field: {
    btn_0: false,
    btn_1: false,
    btn_2: false,
    btn_3: false,
    btn_4: false,
    btn_5: false,
    btn_6: false,
    btn_7: false,
    btn_8: false,
    btn_9: false,
    btn_10: false,
    btn_11: false,
    btn_12: false,
    btn_13: false,
    btn_14: false,
  },
  organizer: {
    btn_0: false,
    btn_1: false,
    btn_2: false,
    btn_3: false,
    btn_4: false,
    btn_5: false,
    btn_6: false,
    btn_7: false,
    btn_8: false,
  },
  district: {
    btn_0: false,
    btn_1: false,
    btn_2: false,
    btn_3: false,
    btn_4: false,
    btn_5: false,
    btn_6: false,
    btn_7: false,
    btn_8: false,
    btn_9: false,
    btn_10: false,
    btn_11: false,
    btn_12: false,
    btn_13: false,
    btn_14: false,
    btn_15: false,
    btn_16: false,
    btn_17: false,
    btn_18: false,
  },
};

export const ContestSelected = {
  type: {
    btn_0: false,
    btn_1: false,
    btn_2: false,
    btn_3: false,
    btn_4: false,
    btn_5: false,
    btn_6: false,
  },
  field: {
    btn_0: false,
    btn_1: false,
    btn_2: false,
    btn_3: false,
    btn_4: false,
    btn_5: false,
    btn_6: false,
    btn_7: false,
    btn_8: false,
    btn_9: false,
    btn_10: false,
    btn_11: false,
    btn_12: false,
    btn_13: false,
    btn_14: false,
  },
  organizer: {
    btn_0: false,
    btn_1: false,
    btn_2: false,
    btn_3: false,
    btn_4: false,
    btn_5: false,
    btn_6: false,
    btn_7: false,
    btn_8: false,
  },
  prize: {
    btn_0: false,
    btn_1: false,
    btn_2: false,
    btn_3: false,
    btn_4: false,
    btn_5: false,
    btn_6: false,
    btn_7: false,
  },
};
